version: 2
updates:
  # Maintain dependencies for NPM
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      npm-dep-updates:
        applies-to: version-updates
        patterns:
          - "*"
      npm-security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  # Maintain dependencies for GH workflows
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
