name: cleanup

on:
  schedule:
  - cron: '0 0 * * *'

  workflow_dispatch: ~

jobs:
  cleanup:
    name: cleanup
    runs-on: ubuntu-20.04
    steps:
    - name: Delete Workflow Runs
      uses: Mattraks/delete-workflow-runs@main
