name: ecbuild

# Controls when the workflow will run
on:

  # Trigger the workflow on all pushes, except on tag creation
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'

  # Allow workflow to be dispatched on demand
  workflow_dispatch: ~

jobs:
  ecbuild:
    name: ecbuild
    strategy:
      matrix:
        name:
        - ubuntu-20.04
        - ubuntu-18.04
        - macos-10.15
        include:
        - name: ubuntu-20.04
          os: ubuntu-20.04
        - name: ubuntu-18.04
          os: ubuntu-18.04
        - name: macos-10.15
          os: macos-10.15
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Checkout ecbuild Repository
      uses: actions/checkout@v3
      with:
        repository: ecmwf/ecbuild
        ref: develop
        path: ${{ github.workspace }}/ecbuild

    - name: Retrieve ecbuild SHA
      working-directory: ${{ github.workspace }}/ecbuild
      shell: bash -eux {0}
      run: echo "ECBUILD_SHA=$(git log -1 --format='%H')" >> $GITHUB_ENV

    - name: Build & Test
      id: build-test
      uses: ./
      with:
        workspace: ${{ github.workspace }}/ecbuild
        repository: ecmwf/ecbuild
        sha: ${{ env.ECBUILD_SHA }}
