name: ecbuild

# Controls when the workflow will run
on:
  # Trigger the workflow on all pushes, except on tag creation
  push:
    branches:
      - main
    tags-ignore:
      - "**"

  # Trigger the workflow on all pull requests
  pull_request: ~

  # Allow workflow to be dispatched on demand
  workflow_dispatch: ~

jobs:
  ecbuild:
    name: ecbuild
    strategy:
      fail-fast: false
      matrix:
        name:
          - ubuntu-24.04
          - ubuntu-22.04
          - macos-latest
        include:
          - name: ubuntu-24.04
            os: ubuntu-24.04
            compiler_fc: gfortran
          - name: ubuntu-22.04
            os: ubuntu-22.04
            compiler_fc: gfortran
          - name: macos-latest
            os: macos-latest
            compiler_fc: gfortran-12
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Checkout ecbuild Repository
        uses: actions/checkout@v4
        with:
          repository: ecmwf/ecbuild
          ref: develop
          path: ${{ github.workspace }}/ecbuild

      - name: Retrieve ecbuild SHA
        working-directory: ${{ github.workspace }}/ecbuild
        shell: bash -eux {0}
        run: echo "ECBUILD_SHA=$(git log -1 --format='%H')" >> $GITHUB_ENV

      - name: Build & Test
        id: build-test
        uses: ./
        with:
          workspace: ${{ github.workspace }}/ecbuild
          repository: ecmwf/ecbuild
          sha: ${{ env.ECBUILD_SHA }}
          compiler_fc: ${{ matrix.compiler_fc }}
